package ccl

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// The fee_payer/from address baked into the testdata/intents/*.yaml fixtures (derived from the
// core test mnemonic). The fixtures are generated by the JVM QuickTxIntentsTest via
// TxPlan.from(tx).toYaml(), so they carry CCL's exact intent YAML shapes; here we drive each one
// through the native library end-to-end to prove the bridge builds it offline (and that the
// native-image reflection config covers the governance/staking/DRep classes).
const intentSender = "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp"

func TestQuickTxIntentsE2E(t *testing.T) {
	files, err := filepath.Glob("testdata/intents/*.yaml")
	if err != nil {
		t.Fatalf("glob fixtures: %v", err)
	}
	if len(files) == 0 {
		t.Fatal("no intent fixtures found in testdata/intents/")
	}

	// A 2000-ADA UTXO at the sender — enough to cover the largest deposit (gov action = 1000 ADA).
	utxos := []map[string]interface{}{{
		"tx_hash":      strings.Repeat("a", 64),
		"output_index": 0,
		"address":      intentSender,
		"amount":       []map[string]interface{}{{"unit": "lovelace", "quantity": "2000000000"}},
	}}

	for _, f := range files {
		name := strings.TrimSuffix(filepath.Base(f), ".yaml")
		t.Run(name, func(t *testing.T) {
			yamlBytes, err := os.ReadFile(f)
			if err != nil {
				t.Fatalf("read %s: %v", f, err)
			}
			result, err := bridge.QuickTx.Build(string(yamlBytes), utxos, testProtocolParams())
			if err != nil {
				t.Fatalf("build %s: %v", name, err)
			}
			if len(result.TxCbor) == 0 {
				t.Error("tx_cbor should not be empty")
			}
			if len(result.TxHash) != 64 {
				t.Errorf("expected 64-char tx_hash, got %d", len(result.TxHash))
			}
			if fee, err := strconv.Atoi(result.Fee); err != nil || fee <= 0 {
				t.Errorf("expected positive fee, got %q", result.Fee)
			}
		})
	}
}
