Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=org.slf4j \
       --initialize-at-build-time=com.bloxbean.cardano.client.crypto \
       --initialize-at-build-time=net.i2p.crypto.eddsa \
       --initialize-at-build-time=com.fasterxml.jackson \
       --initialize-at-build-time=co.nstant.in.cbor
